name: TODO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Deployer
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ubuntu
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                curl -LO https://deployer.org/deployer.phar
                mv deployer.phar /usr/local/bin/dep
                chmod +x /usr/local/bin/dep
                    

      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ubuntu
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                bash -s < serve.sh

      